name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install-node-modules:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build (if applicable)
        run: npm run build --if-present

  test:
    needs: install-node-modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, edge]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Cypress tests in ${{ matrix.browser }}
